import { Open_Sans } from "next/font/google";
import "./globals.css";

// Load Open Sans
const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // add more if needed
  variable: "--font-open-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon/fonts/remixicon.css"
          rel="stylesheet"
        />
      </head>
      <body className={`${openSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
